<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Student;
use App\Models\Mention;
use Illuminate\Support\Str;

class StudentSeeder extends Seeder
{
    public function run(): void
    {
        $mentionInformatique = Mention::where('nom', 'Informatique')->first();
        $mentionGestion = Mention::where('nom', 'Gestion')->first();
        $mentionTheologie = Mention::where('nom', 'Théologie')->first();

        // Exemple de 3 étudiants
        Student::create([
            'nom' => 'Rakoto',
            'prenom' => 'Jean',
            'sexe' => 'M',
            'date_naissance' => '2000-01-15',
            'lieu_naissance' => 'Antananarivo',
            'nationalite' => 'Malagasy',
            'religion' => 'Adventiste',
            'etat_civil' => 'Célibataire',
            'passport_status' => false,
            'passport_numero' => null,
            'passport_pays_emission' => null,
            'passport_date_emission' => null,
            'passport_date_expiration' => null,
            'nom_conjoint' => null,
            'nb_enfant' => 0,
            'cin_numero' => '123456789012',
            'cin_date_delivrance' => '2018-06-01',
            'cin_lieu_delivrance' => 'Antananarivo',
            'nom_pere' => 'Rakoto Pierre',
            'profession_pere' => 'Agriculteur',
            'contact_pere' => '0321234567',
            'nom_mere' => 'Rasoana Marie',
            'profession_mere' => 'Commerçante',
            'contact_mere' => '0327654321',
            'adresse_parents' => 'Lot II, Antananarivo',
            'telephone' => '0341234567',
            'email' => 'jean.rakoto@example.com',
            'adresse' => 'Antananarivo',
            'region' => 'Analamanga',
            'district' => 'Antananarivo Renivohitra',
            'bacc_serie' => 'C',
            'bacc_date_obtention' => '2017-09-01',
            'bursary_status' => false,
            'sponsor_nom' => null,
            'sponsor_prenom' => null,
            'sponsor_telephone' => null,
            'sponsor_adresse' => null,
            'annee_etude' => 1,
            'mention_id' => $mentionInformatique ? $mentionInformatique->id : null,
            'matricule' => '30188',
        ]);

        Student::create([
            'nom' => 'Rabe',
            'prenom' => 'Marie',
            'sexe' => 'F',
            'date_naissance' => '2001-05-20',
            'lieu_naissance' => 'Fianarantsoa',
            'nationalite' => 'Malagasy',
            'religion' => 'Catholique',
            'etat_civil' => 'Célibataire',
            'passport_status' => false,
            'passport_numero' => null,
            'passport_pays_emission' => null,
            'passport_date_emission' => null,
            'passport_date_expiration' => null,
            'nom_conjoint' => null,
            'nb_enfant' => 0,
            'cin_numero' => '987654321098',
            'cin_date_delivrance' => '2019-07-10',
            'cin_lieu_delivrance' => 'Fianarantsoa',
            'nom_pere' => 'Rabe Jean',
            'profession_pere' => 'Fonctionnaire',
            'contact_pere' => '0331234567',
            'nom_mere' => 'Rabe Lucie',
            'profession_mere' => 'Enseignante',
            'contact_mere' => '0337654321',
            'adresse_parents' => 'Lot III, Fianarantsoa',
            'telephone' => '0347654321',
            'email' => 'marie.rabe@example.com',
            'adresse' => 'Fianarantsoa',
            'region' => 'Haute Matsiatra',
            'district' => 'Fianarantsoa I',
            'bacc_serie' => 'A2',
            'bacc_date_obtention' => '2018-09-01',
            'bursary_status' => true,
            'sponsor_nom' => 'Sponsor',
            'sponsor_prenom' => 'Paul',
            'sponsor_telephone' => '0349999999',
            'sponsor_adresse' => 'Antsirabe',
            'annee_etude' => 2,
            'mention_id' => $mentionGestion ? $mentionGestion->id : null,
            'matricule' => '20149',
        ]);

        Student::create([
            'nom' => 'Andrianina',
            'prenom' => 'Paul',
            'sexe' => 'M',
            'date_naissance' => '1999-11-30',
            'lieu_naissance' => 'Toamasina',
            'nationalite' => 'Malagasy',
            'religion' => 'Protestant',
            'etat_civil' => 'Célibataire',
            'passport_status' => false,
            'passport_numero' => null,
            'passport_pays_emission' => null,
            'passport_date_emission' => null,
            'passport_date_expiration' => null,
            'nom_conjoint' => null,
            'nb_enfant' => 0,
            'cin_numero' => '112233445566',
            'cin_date_delivrance' => '2017-03-15',
            'cin_lieu_delivrance' => 'Toamasina',
            'nom_pere' => 'Andrianina Joseph',
            'profession_pere' => 'Chauffeur',
            'contact_pere' => '0328888888',
            'nom_mere' => 'Andrianina Rose',
            'profession_mere' => 'Couturière',
            'contact_mere' => '0327777777',
            'adresse_parents' => 'Lot IV, Toamasina',
            'telephone' => '0342222222',
            'email' => 'paul.andrianina@example.com',
            'adresse' => 'Toamasina',
            'region' => 'Atsinanana',
            'district' => 'Toamasina I',
            'bacc_serie' => 'D',
            'bacc_date_obtention' => '2016-09-01',
            'bursary_status' => false,
            'sponsor_nom' => null,
            'sponsor_prenom' => null,
            'sponsor_telephone' => null,
            'sponsor_adresse' => null,
            'annee_etude' => 3,
            'mention_id' => $mentionTheologie ? $mentionTheologie->id : null,
            'matricule' => '10999',
        ]);

        // Étudiants issus du fichier SQL (exemples)
        Student::create([
            'nom' => 'Rabenamana',
            'prenom' => 'Hary Lala',
            'sexe' => 'M',
            'date_naissance' => '2001-11-09',
            'lieu_naissance' => 'Pavillon Sante Fleur Antananarivo',
            'nationalite' => 'Malagasy',
            'religion' => 'Adventiste',
            'etat_civil' => 'Célibataire',
            'passport_status' => false,
            'passport_numero' => null,
            'passport_pays_emission' => null,
            'passport_date_emission' => null,
            'passport_date_expiration' => null,
            'nom_conjoint' => null,
            'nb_enfant' => 0,
            'cin_numero' => '719011043806',
            'cin_date_delivrance' => null,
            'cin_lieu_delivrance' => null,
            'nom_pere' => 'Rabenamana Charlin',
            'profession_pere' => 'Pasteur',
            'contact_pere' => null,
            'nom_mere' => 'Rasendrarisoa Annie',
            'profession_mere' => 'Ménagère',
            'contact_mere' => null,
            'adresse_parents' => null,
            'telephone' => '032 58 551 86',
            'email' => 'rabenamana.h@zurcher.edu.mg',
            'adresse' => 'Antsiranana (Antsiranana I - Antsiranana Urban) ()',
            'region' => '5',
            'district' => null,
            'bacc_serie' => null,
            'bacc_date_obtention' => null,
            'bursary_status' => false,
            'sponsor_nom' => null,
            'sponsor_prenom' => null,
            'sponsor_telephone' => null,
            'sponsor_adresse' => null,
            'annee_etude' => 3,
            'mention_id' => $mentionInformatique ? $mentionInformatique->id : null,
            'matricule' => '30188',
        ]);

        Student::create([
            'nom' => 'Volaniaina',
            'prenom' => 'Olga Henriette',
            'sexe' => 'F',
            'date_naissance' => '2004-10-04',
            'lieu_naissance' => 'Toamasina II',
            'nationalite' => 'Malagasy',
            'religion' => 'non Adventiste',
            'etat_civil' => 'Célibataire',
            'passport_status' => false,
            'passport_numero' => null,
            'passport_pays_emission' => null,
            'passport_date_emission' => null,
            'passport_date_expiration' => null,
            'nom_conjoint' => null,
            'nb_enfant' => 0,
            'cin_numero' => null,
            'cin_date_delivrance' => null,
            'cin_lieu_delivrance' => null,
            'nom_pere' => null,
            'profession_pere' => null,
            'contact_pere' => null,
            'nom_mere' => null,
            'profession_mere' => null,
            'contact_mere' => null,
            'adresse_parents' => null,
            'telephone' => '0340178011',
            'email' => 'volaniaina.o@zurcher.edu.mg',
            'adresse' => 'Andranomadio P/elle 11/43',
            'region' => '12',
            'district' => null,
            'bacc_serie' => null,
            'bacc_date_obtention' => null,
            'bursary_status' => true,
            'sponsor_nom' => 'HELP MADAGASCAR',
            'sponsor_prenom' => null,
            'sponsor_telephone' => null,
            'sponsor_adresse' => null,
            'annee_etude' => 2,
            'mention_id' => $mentionInformatique ? $mentionInformatique->id : null,
            'matricule' => '30202',
        ]);

        Student::create([
            'nom' => 'Ranala',
            'prenom' => 'Miary Manaja Esaï Ny Aina',
            'sexe' => 'M',
            'date_naissance' => '2002-10-07',
            'lieu_naissance' => 'Bejofo - Ambatondrazaka',
            'nationalite' => 'Malagasy',
            'religion' => 'Adventiste du Septieme-jour',
            'etat_civil' => 'Célibataire',
            'passport_status' => false,
            'passport_numero' => null,
            'passport_pays_emission' => null,
            'passport_date_emission' => null,
            'passport_date_expiration' => null,
            'nom_conjoint' => null,
            'nb_enfant' => 0,
            'cin_numero' => null,
            'cin_date_delivrance' => null,
            'cin_lieu_delivrance' => null,
            'nom_pere' => 'Ranala Marc Arthur',
            'profession_pere' => 'Pasteur',
            'contact_pere' => null,
            'nom_mere' => 'Ramiarisoa Bakolimalala Charline',
            'profession_mere' => 'Infirmière',
            'contact_mere' => null,
            'adresse_parents' => null,
            'telephone' => '0328985686',
            'email' => 'ranala.m@zurcher.edu.mg',
            'adresse' => 'Antsampanimahazo (Ambohibary - Antsirabe Rural)',
            'region' => '4',
            'district' => null,
            'bacc_serie' => null,
            'bacc_date_obtention' => null,
            'bursary_status' => false,
            'sponsor_nom' => null,
            'sponsor_prenom' => null,
            'sponsor_telephone' => null,
            'sponsor_adresse' => null,
            'annee_etude' => 3,
            'mention_id' => $mentionInformatique ? $mentionInformatique->id : null,
            'matricule' => '30152',
        ]);
        // ...Ajoutez ici les autres étudiants du SQL en suivant ce modèle...
    }
}